# Generated by Django 4.2.18 on 2026-06-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(help_text='Código do instrutor', primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Informe o RG do instrutor', max_length=20)),
                ('nome', models.CharField(help_text='Informe o nome do instrutor', max_length=100)),
                ('dataNascimento', models.DateField(help_text='Informe a data de nascimento')),
                ('telefone', models.CharField(help_text='Informe o telefone', max_length=15)),
                ('ddd', models.CharField(help_text='Informe o DDD', max_length=2)),
                ('codigoTitulo', models.IntegerField(help_text='Informe o código do título')),
            ],
        ),
    ]
