# Generated by Django 4.2.18 on 2026-06-11 00:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '0002_rename_descrcao_titulo_descricao_alter_titulo_codigo'),
        ('instrutor', '0002_alter_instrutor_codigotitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrutor',
            name='codigoTitulo',
            field=models.ForeignKey(blank=True, db_column='codigoTitulo', help_text='Informe o código do título', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='titulos', to='titulo.titulo'),
        ),
    ]
