# Generated by Django 4.2.18 on 2026-06-10 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tipoatividade',
            fields=[
                ('codigo', models.AutoField(help_text='Código do tipo atividade', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe o tipo de atividade', max_length=70)),
            ],
        ),
    ]
