# Generated by Django 4.2.18 on 2026-06-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(help_text='Matrícula do aluno', primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do aluno', max_length=70)),
                ('dataInicial', models.DateField(help_text='Informe a data inicial')),
                ('dataFinal', models.DateField(help_text='Informe a data final')),
            ],
        ),
    ]
