# Generated by Django 4.2.18 on 2026-06-09 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='titulo',
            old_name='descrcao',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='titulo',
            name='codigo',
            field=models.AutoField(help_text='Código do título', primary_key=True, serialize=False),
        ),
    ]
