# Generated by Django 4.2.18 on 2026-06-10 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('numero', models.AutoField(help_text='Número da turma', primary_key=True, serialize=False)),
                ('horarioAula', models.TimeField(help_text='Horário da aula')),
                ('duracaoAula', models.IntegerField(help_text='Duração da aula em minutos')),
                ('dataInicial', models.DateField(help_text='Data inicial da turma')),
                ('dataFinal', models.DateField(help_text='Data final da turma')),
                ('matriculaMonitor', models.IntegerField(help_text='Matrícula do monitor')),
                ('idInstrutor', models.IntegerField(help_text='ID do instrutor')),
            ],
        ),
    ]
